# Generated by Django 2.1.2 on 2018-10-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RTO_Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100, unique=True)),
                ('reg_number', models.IntegerField()),
                ('validity', models.DateField()),
                ('vehicle_type', models.CharField(max_length=40)),
                ('order_number', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'rto_details',
                'managed': True,
            },
        ),
    ]
