# Generated by Django 2.1.2 on 2018-10-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexiiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rto_details',
            name='reg_number',
            field=models.TextField(),
        ),
    ]
